### ISSUE TITLE
"Install directly from github"

### ISSUE THREAD

**Issue by thealexofevil** [iFelix18/Darkt#5]
Your other scripts have an option "Install directly from github" that works wonderfully with GreaseMonkey/TamperMonkey but I can't seem to install this.

Perhaps because it's a .css and not a .js, I don't know.

Just pasting the code doesn't work either, nor does installing from URL.

Just thought I'd let you know. Thanks.

**Comment by iFelix18** [comment]
This is not a userscript, but a userstyle. It doesn't work with GreaseMonkey/TamperMonkey because they are userscripts managers, you need a userstyles manager.

Read how to install it, and which userstyles managers to use, in the [readme](https://github.com/iFelix18/Darkt/blob/master/README.md#how-to-install).
